name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "CI"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.2"
      - run: go vet
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          install-go: false
